export const WORDS = [
  { word: "tunnag", ipa: "/ˈtʰun̪ˠak/" },
  { word: "snog", ipa: "/sn̪ˠok/" },
  { word: "seo", ipa: "/ʃɔ/" },
  { word: "piseag", ipa: "/ˈpʰiʃak/" },
  { word: "muc", ipa: "/muxk/" },
  { word: "Mòrag", ipa: "/ˈmoːɾak/" },
  { word: "mòr", ipa: "/ˈmoːɾ/" },
  { word: "math", ipa: "/maː/" },
  { word: "Irn bru", ipa: "no ipa found" },
  { word: "Iain", ipa: "/iaɲ/" },
  { word: "gàidhlig", ipa: "no ipa found" },
  { word: "Eilidh", ipa: "no ipa found" },
  { word: "dona", ipa: "/ˈt̪ɔnə/" },
  { word: "cù", ipa: "/kʰuː/" },
  { word: "cearc", ipa: "/kʲʰɛɾxk/" },
  { word: "cat", ipa: "/kʰaʰt̪/" },
  { word: "caraid", ipa: "/kʰaɾɪtʲ/" },
  { word: "Calum", ipa: "/ˈkʰal̪ˠəm/" },
  { word: "caileag", ipa: "/ˈkʰalak/" },
  { word: "bò", ipa: "/poː/" },
  { word: "beag", ipa: "/pek/" },
  { word: "balach", ipa: "/ˈpal̪ˠəx/" },
  { word: "Anna", ipa: "/ˈan̪ˠa/" },
  { word: "agus", ipa: "/ˈakəs/" },
];
